### ISSUE TITLE
ticce.md GitHubをマスターする方法

### ISSUE THREAD

**Issue by Ticce** [stop-covid19-hyogo/covid19hyogo-sandbox#8]
サンプルです。

**Comment by Ticce** [comment]
具体的な方法を細かく書くと良い。巨大になると解決に誰も手を上げないから。

**Comment by ohyama** [comment]
GitHubをマスターする方法って具体的にはどんなことが知りたいですか？
参考サイトなどをリストすればよいでしょうか？

**Comment by Ticce** [comment]
いきなり、本番で使って消したり、変なところに送らないかが、心配になります。

**Comment by ohyama** [comment]
大丈夫です！更新権限を持っているのはコミッターと呼ばれる、ちゃんと知識のある人だけなので、プロジェクトを壊すような変更は、そもそもマージされません。

**Comment by ohyama** [comment]
変なところに送っても無視されるだけです… もし違うリポジトリに pull request を送ってしまった場合は、「間違えました」と自分でクローズしに行けば大丈夫です。

**Comment by Ticce** [comment]
安心しました！

**Comment by ohyama** [comment]
こんなページを見つけたのでここを追加します！

https://qiita.com/nnahito/items/565f8755e70c51532459

**Comment by ohyama** [comment]
修正しました！ご確認お願いします！

https://github.com/stop-covid19-hyogo/covid19hyogo-sandbox/pull/11

**Comment by ohyama** [comment]
上記で対応したのでクローズします！
